name: "Hello Actions!"

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Greeting"
        run: "echo 'Hei på deg GitHub Actions!'"
      - name: "Echo Er på kurs!"
        run: "echo 'Er på kurs og lærer greier!'"
      - name: "Echo Goodnight"
        run: "echo 'Natta!'"
